# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Xilinx/Vivado/2015.2/progetti/WP1/WP1.srcs/constrs_1/imports/WP1/roberto_constraints.xdc

# XDC: C:/Xilinx/Vivado/2015.2/progetti/WP1/WP1.srcs/constrs_1/new/migrated_io_properties.xdc

# Block Designs: bd/WP1_system/WP1_system.bd
# Block Designs: The module: 'WP1_system' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/WP1_system/ip/WP1_system_processing_system7_0_0/WP1_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_processing_system7_0_0 || ORIG_REF_NAME==WP1_system_processing_system7_0_0}]

# IP: bd/WP1_system/ip/WP1_system_axi_gpio_0_0/WP1_system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_axi_gpio_0_0 || ORIG_REF_NAME==WP1_system_axi_gpio_0_0}]

# IP: bd/WP1_system/ip/WP1_system_processing_system7_0_axi_periph_0/WP1_system_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==WP1_system_processing_system7_0_axi_periph_0}]

# IP: bd/WP1_system/ip/WP1_system_rst_processing_system7_0_100M_0/WP1_system_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==WP1_system_rst_processing_system7_0_100M_0}]

# IP: bd/WP1_system/ip/WP1_system_util_ds_buf_0_0/WP1_system_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_util_ds_buf_0_0 || ORIG_REF_NAME==WP1_system_util_ds_buf_0_0}]

# IP: bd/WP1_system/ip/WP1_system_selectio_wiz_0_0/WP1_system_selectio_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_selectio_wiz_0_0 || ORIG_REF_NAME==WP1_system_selectio_wiz_0_0}]

# IP: bd/WP1_system/ip/WP1_system_xlconstant_0_0/WP1_system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_xlconstant_0_0 || ORIG_REF_NAME==WP1_system_xlconstant_0_0}]

# IP: bd/WP1_system/ip/WP1_system_selectio_wiz_1_0/WP1_system_selectio_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_selectio_wiz_1_0 || ORIG_REF_NAME==WP1_system_selectio_wiz_1_0}]

# IP: bd/WP1_system/ip/WP1_system_util_vector_logic_0_0/WP1_system_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_util_vector_logic_0_0 || ORIG_REF_NAME==WP1_system_util_vector_logic_0_0}]

# IP: bd/WP1_system/ip/WP1_system_Interface_ADC_0_2/WP1_system_Interface_ADC_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_Interface_ADC_0_2 || ORIG_REF_NAME==WP1_system_Interface_ADC_0_2}]

# IP: bd/WP1_system/ip/WP1_system_delay_input_0_1/WP1_system_delay_input_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_delay_input_0_1 || ORIG_REF_NAME==WP1_system_delay_input_0_1}]

# IP: bd/WP1_system/ip/WP1_system_blk_mem_gen_0_2/WP1_system_blk_mem_gen_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_blk_mem_gen_0_2 || ORIG_REF_NAME==WP1_system_blk_mem_gen_0_2}]

# IP: bd/WP1_system/ip/WP1_system_axi_bram_ctrl_0_1/WP1_system_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_axi_bram_ctrl_0_1 || ORIG_REF_NAME==WP1_system_axi_bram_ctrl_0_1}]

# IP: bd/WP1_system/ip/WP1_system_axi_bram_ctrl_1_0/WP1_system_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_axi_bram_ctrl_1_0 || ORIG_REF_NAME==WP1_system_axi_bram_ctrl_1_0}]

# IP: bd/WP1_system/ip/WP1_system_blk_mem_gen_1_0/WP1_system_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_blk_mem_gen_1_0 || ORIG_REF_NAME==WP1_system_blk_mem_gen_1_0}]

# IP: bd/WP1_system/ip/WP1_system_xbar_0/WP1_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_xbar_0 || ORIG_REF_NAME==WP1_system_xbar_0}]

# IP: bd/WP1_system/ip/WP1_system_s00_data_fifo_0_1/WP1_system_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_s00_data_fifo_0 || ORIG_REF_NAME==WP1_system_s00_data_fifo_0}]

# IP: bd/WP1_system/ip/WP1_system_auto_pc_0/WP1_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_auto_pc_0 || ORIG_REF_NAME==WP1_system_auto_pc_0}]

# IP: bd/WP1_system/ip/WP1_system_auto_pc_1_1/WP1_system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_auto_pc_1 || ORIG_REF_NAME==WP1_system_auto_pc_1}]

# IP: bd/WP1_system/ip/WP1_system_auto_pc_2/WP1_system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_auto_pc_2 || ORIG_REF_NAME==WP1_system_auto_pc_2}]

# XDC: bd/WP1_system/ip/WP1_system_processing_system7_0_0/WP1_system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==WP1_system_processing_system7_0_0 || ORIG_REF_NAME==WP1_system_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/WP1_system/ip/WP1_system_axi_gpio_0_0/WP1_system_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==WP1_system_axi_gpio_0_0 || ORIG_REF_NAME==WP1_system_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/WP1_system/ip/WP1_system_axi_gpio_0_0/WP1_system_axi_gpio_0_0_ooc.xdc

# XDC: bd/WP1_system/ip/WP1_system_axi_gpio_0_0/WP1_system_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==WP1_system_axi_gpio_0_0 || ORIG_REF_NAME==WP1_system_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/WP1_system/ip/WP1_system_rst_processing_system7_0_100M_0/WP1_system_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==WP1_system_rst_processing_system7_0_100M_0}]

# XDC: bd/WP1_system/ip/WP1_system_rst_processing_system7_0_100M_0/WP1_system_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WP1_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==WP1_system_rst_processing_system7_0_100M_0}]

# XDC: bd/WP1_system/ip/WP1_system_rst_processing_system7_0_100M_0/WP1_system_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/WP1_system/ip/WP1_system_selectio_wiz_0_0/WP1_system_selectio_wiz_0_0_ooc.xdc

# XDC: bd/WP1_system/ip/WP1_system_selectio_wiz_0_0/WP1_system_selectio_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==WP1_system_selectio_wiz_0_0 || ORIG_REF_NAME==WP1_system_selectio_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/WP1_system/ip/WP1_system_selectio_wiz_1_0/WP1_system_selectio_wiz_1_0_ooc.xdc

# XDC: bd/WP1_system/ip/WP1_system_selectio_wiz_1_0/WP1_system_selectio_wiz_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==WP1_system_selectio_wiz_1_0 || ORIG_REF_NAME==WP1_system_selectio_wiz_1_0}] {/U0 }]/U0 ]]

# XDC: bd/WP1_system/ip/WP1_system_blk_mem_gen_0_2/WP1_system_blk_mem_gen_0_2_ooc.xdc

# XDC: bd/WP1_system/ip/WP1_system_axi_bram_ctrl_0_1/WP1_system_axi_bram_ctrl_0_1_ooc.xdc

# XDC: bd/WP1_system/ip/WP1_system_axi_bram_ctrl_1_0/WP1_system_axi_bram_ctrl_1_0_ooc.xdc

# XDC: bd/WP1_system/ip/WP1_system_blk_mem_gen_1_0/WP1_system_blk_mem_gen_1_0_ooc.xdc

# XDC: bd/WP1_system/ip/WP1_system_xbar_0/WP1_system_xbar_0_ooc.xdc

# XDC: bd/WP1_system/ip/WP1_system_s00_data_fifo_0_1/WP1_system_s00_data_fifo_0_ooc.xdc

# XDC: bd/WP1_system/ip/WP1_system_auto_pc_0/WP1_system_auto_pc_0_ooc.xdc

# XDC: bd/WP1_system/ip/WP1_system_auto_pc_1_1/WP1_system_auto_pc_1_ooc.xdc

# XDC: bd/WP1_system/ip/WP1_system_auto_pc_2/WP1_system_auto_pc_2_ooc.xdc

# XDC: bd/WP1_system/WP1_system_ooc.xdc
