
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xspips.h"

/*
* The configuration table for devices
*/

XSpiPs_Config XSpiPs_ConfigTable[] =
{
	{
		XPAR_PS7_SPI_1_DEVICE_ID,
		XPAR_PS7_SPI_1_BASEADDR,
		XPAR_PS7_SPI_1_SPI_CLK_FREQ_HZ
	}
};


